channels:
- conda-forge
# For jupyter-desktop-server
- manics

# Almost all libraries should be added in requirements.txt
# Only libraries *not* available in PyPI should be here
dependencies:
- python=3.9.*

# Visual Studio Code!
- jupyter-vscode-proxy
- code-server

# A linux desktop environment
- websockify # from manics channel

- pip
- pip:
  - -r requirements.txt